// Import createSlice function from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit';

// Define the initial state of the balance
const initialState = { value: 0 };

// Define the balance slice using createSlice function
const balanceSlice = createSlice({
  name: 'balance',
  initialState,
  reducers: {
    deposit: (state, action) => {
      state.value += action.payload;
      state.value = parseFloat(state.value.toFixed(2));
    },
    withdraw: (state, action) => {
      state.value -= action.payload;
      state.value = parseFloat(state.value.toFixed(2));
    },
    addInterest: (state) => {
      const rate = 0.05;
      const interest = state.value * rate;
      state.value += interest;
      state.value = parseFloat(state.value.toFixed(2));
    },
    charge: (state) => {
      const deduction = state.value * 0.15;
      state.value -= deduction;
      state.value = parseFloat(state.value.toFixed(2));
    }
  }
});

// Extract the reducer functions from the slice object
export const { deposit, withdraw, addInterest, charge } = balanceSlice.actions;

// Export the reducer function generated by the slice
export default balanceSlice.reducer;
